services:
  db:
    image: postgis/postgis:15-3.5-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/prisma/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: always
    ports:
      - "5672:5672" 
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}  
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s      

  redis:
    image: redis:alpine   
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 30s
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - BACKEND_URL=${BACKEND_URL}
      - FRONTEND_URL=${FRONTEND_URL}        
      - KHALTI_BASE_URL=${KHALTI_BASE_URL} 
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - RABBITMQ_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672
      - REDIS_URL=${REDIS_URL}
      - KHALTI_SECRET_KEY=${KHALTI_SECRET_KEY}
      - NODE_ENV=development
    depends_on: 
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: >
      sh -c "npx prisma generate &&
      until npx prisma migrate deploy; do echo 'Waiting for DB...'; sleep 3; done &&
      until node prisma/seed.js; do echo 'Seed failed, retrying...'; sleep 3; done &&
      npm run dev"
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    stdin_open: true
    env_file:
      - .env
    environment:
      - VITE_API_URL=http://localhost:3000
      - VITE_KHALTI_PUBLIC_KEY=${KHALTI_PUBLIC_KEY}
    depends_on:
      - server
  
volumes:
  postgres_data:
  rabbitmq_data: